config/routes.rb
# == Route Map
#
#       Prefix Verb   URI Pattern                      Controller#Action
#         feed GET    /feed(.:format)                  feeds#show
#      session POST   /session(.:format)               sessions#create
#  new_session GET    /session/new(.:format)           sessions#new
#              DELETE /session(.:format)               sessions#destroy
#       tweets POST   /tweets(.:format)                tweets#create
# search_users GET    /users/search(.:format)          users#search
#  user_follow POST   /users/:user_id/follow(.:format) follows#create
#              DELETE /users/:user_id/follow(.:format) follows#destroy
#        users POST   /users(.:format)                 users#create
#     new_user GET    /users/new(.:format)             users#new
#         user GET    /users/:id(.:format)             users#show
#         root GET    /                                redirect(301, /feed)
#

AjaxTwitter::Application.routes.draw do
  resource :feed, only: [:show]
  resource :session, only: [:create, :destroy, :new]
  resources :tweets, only: [:create]
  resources :users, only: [:create, :new, :show] do
    get "search", on: :collection

    resource :follow, only: [:create, :destroy]
  end

  root to: redirect("/feed")
end

app/models/tweet.rb
# == Schema Information
#
# Table name: tweets
#
#  id         :integer          not null, primary key
#  content    :text             not null
#  user_id    :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class Tweet < ActiveRecord::Base
  has_many :mentions
  has_many :mentioned_users, through: :mentions, source: :user
  belongs_to :user

  validates :content, :user, presence: true
end

app/controllers/tweets_controller.rb
# == Schema Information
#
# Table name: tweets
#
#  id         :integer          not null, primary key
#  content    :text             not null
#  user_id    :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class TweetsController < ApplicationController
  before_action :require_logged_in!

  def create
    # simulate latency
    sleep(1)

    @tweet = current_user.tweets.build(tweet_params)

    if @tweet.save
      respond_to do |format|
        format.html { redirect_to request.referrer }
        format.json { render :show }
      end
    else
      # Lazy: even respond with JSON to invalid HTML request.
      render json: @tweet.errors.full_messages, status: 422
    end
  end

  private
  def tweet_params
    params.require(:tweet).permit(:content, mentioned_user_ids: [])
  end
end

app/views/tweets/_form.html.erb
<h2>New Tweet!</h2>
<form action="/tweets" method="POST">
  <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">

  <label>
    Content
    <textarea name="tweet[content]"></textarea>
  </label>
  <br>

  <label>
    Mention
    <select name="tweet[mentioned_user_ids][]">
      <option></option>
      <% User.all.each do |user| %>
        <option value="<%= user.id %>"><%= user.username %></option>
      <% end %>
    </select>
  </label>
  <br>

  <input type="Submit" value="Post Tweet!">
</form>

app/views/tweets/_tweet.html.erb
<%= tweet.content %>
-- <%= link_to tweet.user.username, user_url(tweet.user.id) %>
-- <%= tweet.created_at %>

<% if tweet.mentioned_users.length > 0 %>
  <ul>
    <% tweet.mentioned_users.each do |mentioned_user| %>
      <li><%= link_to mentioned_user.username, user_url(mentioned_user) %></li>
    <% end %>
  </ul>
<% end %>