config/routes.rb
# == Route Map
#
#       Prefix Verb   URI Pattern                      Controller#Action
#         feed GET    /feed(.:format)                  feeds#show
#      session POST   /session(.:format)               sessions#create
#  new_session GET    /session/new(.:format)           sessions#new
#              DELETE /session(.:format)               sessions#destroy
#       tweets POST   /tweets(.:format)                tweets#create
# search_users GET    /users/search(.:format)          users#search
#  user_follow POST   /users/:user_id/follow(.:format) follows#create
#              DELETE /users/:user_id/follow(.:format) follows#destroy
#        users POST   /users(.:format)                 users#create
#     new_user GET    /users/new(.:format)             users#new
#         user GET    /users/:id(.:format)             users#show
#         root GET    /                                redirect(301, /feed)
#

AjaxTwitter::Application.routes.draw do
  resource :feed, only: [:show]
  resource :session, only: [:create, :destroy, :new]
  resources :tweets, only: [:create]
  resources :users, only: [:create, :new, :show] do
    get "search", on: :collection

    resource :follow, only: [:create, :destroy]
  end

  root to: redirect("/feed")
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AjaxTwitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<ul>
  <li><%= link_to "Feed", feed_url %></li>
  <li><%= link_to "User Search", search_users_url %></li>
</ul>

<% if current_user %>
  <form action="/session" method="POST">
    <input type="hidden" name="_method" value="DELETE">
    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">

    <input type="submit" value="Logout!">
  </form>
<% end %>

<%= yield %>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>